---
host_baseline_packages: []
host_baseline_kernel_modules:
  - overlay
  - br_netfilter
host_baseline_sysctl: {}
host_baseline_disable_swap: true
host_baseline_enable_time_sync: true
host_baseline_validate_nvidia: true
host_baseline_expected_gpu_count: 4
host_baseline_expected_gpu_model_pattern: "RTX 4090"
host_baseline_expected_driver_branch_pattern: "^580\\."
