"""create jobs table

Revision ID: b2189242c238
Revises: 
Create Date: 2026-08-13 23:32:39.919929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2189242c238'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('VALIDATED', 'QUEUED', 'RUNNING', 'RETRYING', 'SUCCEEDED', 'FAILED', name='job_state', native_enum=False, create_constraint=True), server_default='VALIDATED', nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('image_uri', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('runtime_version', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('retry_count >= 0', name='ck_jobs_retry_count_nonnegative'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
