"""add dispatch outbox

Revision ID: c5b187f676c4
Revises: fcc1ac6bdf87
Create Date: 2026-08-16 23:39:54.458157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b187f676c4'
down_revision: Union[str, Sequence[str], None] = 'fcc1ac6bdf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_outbox',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redis_message_id', sa.String(length=100), nullable=True),
    sa.Column('claimed_by', sa.String(length=255), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('job_id', 'event_type', name='uq_dispatch_outbox_job_event')
    )
    op.create_index(op.f('ix_dispatch_outbox_claim_expires_at'), 'dispatch_outbox', ['claim_expires_at'], unique=False)
    op.create_index(op.f('ix_dispatch_outbox_job_id'), 'dispatch_outbox', ['job_id'], unique=False)
    op.create_index(op.f('ix_dispatch_outbox_published_at'), 'dispatch_outbox', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_outbox_published_at'), table_name='dispatch_outbox')
    op.drop_index(op.f('ix_dispatch_outbox_job_id'), table_name='dispatch_outbox')
    op.drop_index(op.f('ix_dispatch_outbox_claim_expires_at'), table_name='dispatch_outbox')
    op.drop_table('dispatch_outbox')
    # ### end Alembic commands ###
