"""replace image uri with object storage metadata

Revision ID: fcc1ac6bdf87
Revises: b2189242c238
Create Date: 2026-08-15 00:23:12.343710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc1ac6bdf87'
down_revision: Union[str, Sequence[str], None] = 'b2189242c238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('image_bucket', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('image_object_key', sa.Text(), nullable=False))
    op.add_column('jobs', sa.Column('image_content_type', sa.String(length=100), nullable=False))
    op.add_column('jobs', sa.Column('image_size_bytes', sa.BigInteger(), nullable=False))
    op.drop_column('jobs', 'image_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('image_uri', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'image_size_bytes')
    op.drop_column('jobs', 'image_content_type')
    op.drop_column('jobs', 'image_object_key')
    op.drop_column('jobs', 'image_bucket')
    # ### end Alembic commands ###
